#!/usr/bin/env bash
# This is a factors challenge

check_factor() {
    if [ $# -ne 1 ]; then
        echo "Usage: check_factor <number>"
        exit 1
    fi

    factors=$(factor "$1" | cut -d' ' -f2-)
    factors_array=($factors)

    if [ ${#factors_array[@]} -le 2 ]; then
        echo "$1=1*$1"
    else
        max_factor=${factors_array[-1]}
        second_max_factor=${factors_array[-2]}

        for ((i=${#factors_array[@]}-1; i>=0; i--)); do
            if [ $((factors_array[i]*second_max_factor)) -gt $((max_factor*factors_array[i+1])) ]; then
                break
            fi

            second_max_factor=${factors_array[i]}
        done

        echo "$1=$max_factor*$second_max_factor"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
elif ! [ -f "$1" ] || ! [ -r "$1" ]; then
    echo "Error: $1 cannot be opened or read"
    exit 1
else
    while read -r number; do
        check_factor "$number"
    done < "$1"
fi
