#!/usr/bin/env bash

check_factor() {
    if [ $# -ne 1 ]; then
        args=("$@")
        num1=0
        num2=0
        for ((i = 0; i < ${#args[@]}; i++)); do
            if (( ${args[i]} > num1 )); then
                num2=$num1
                num1=${args[i]}
            elif (( ${args[i]} > num2 )); then
                num2=${args[i]}
            fi
        done
    else
        num1=$1
        num2=1
    fi

    echo "${num1}:${num2}=$((num1*num2))"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r i; do
        result=$(factor "$i")
        check_factor $(echo "$result" | awk '{print $(NF-1),$NF}')
    done < "$1"
fi
