#!/usr/bin/env bash

check_factor() {
    if [ $# -ne 1 ]; then
        args=("$@")
        num1=1
        num2=1
        for a in "${args[@]}"; do
            if [ "$a" -gt "$num1" ]; then
                num2=$num1
                num1=$a
            elif [ "$a" -gt "$num2" ]; then
                num2=$a
            fi
        done
    else
        num1=$1
        num2=1
    fi

    num=$(echo "$num1 * $num2" | bc)

    echo "${num1}:${num2}=${num}"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r i; do
        result=$(factor "$i")
        check_factor ${result[@]}
    done < "$1"
fi
